#!/bin/bash
set -o errtrace
set -o functrace
set -o errexit
set -o nounset
set -o pipefail
export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
export DEBIAN_FRONTEND=noninteractive
rm -rf /tmp/hashicorp && \
mkdir -p /tmp/hashicorp && \
curl -sL "https://releases.hashicorp.com/index.json" | jq -r '[to_entries | map_values(.value + { slug: .key }) |.[].versions | to_entries | map_values(.value + { slug: .key }) | [.[].builds[] | select( (.version | ( contains("ent") or contains("beta") or contains("rc") or contains("techpreview"))|not) and (.name=="vagrant") and (.os=="linux") and (.arch=="amd64") and (.url | contains("zip")) and (.version | contains("-") | not) and (.name | ( contains("provider") or contains("null") or contains("-"))|not))] | max_by(.version | [splits("[.]")] | map(tonumber))] | del(.[] | nulls) | .[] | "wget -O \"/tmp/hashicorp/\(.name).zip\" \"\(.url)\""' | xargs -I {} -P `nproc` bash -c "{}" && \
pushd /tmp/hashicorp && \
find . -mindepth 1 -maxdepth 1 -type f -name '*.zip' | xargs -I {} -P `nproc` unzip {} && \
rm *.zip && \
sudo mv -f ./* /usr/local/bin/ && \
popd 
# => vagrant without sudo
# => https://gist.github.com/elvetemedve/c3574e5cadbcddef0b85
sudo tee /etc/sudoers.d/vagrant > /dev/null << EOF
Cmnd_Alias VAGRANT_HOSTS_ADD = /bin/sh -c echo "*" >> /etc/hosts
Cmnd_Alias VAGRANT_HOSTS_REMOVE = /usr/bin/sed -i -e /*/ d /etc/hosts
%sudo ALL=(root) NOPASSWD: VAGRANT_HOSTS_ADD, VAGRANT_HOSTS_REMOVE
Cmnd_Alias VAGRANT_EXPOSTS_UPDATE = /usr/bin/chown 0\:0 /tmp/*, /usr/bin/mv -f /tmp/* /etc/exports
Cmnd_Alias VAGRANT_EXPORTS_ADD = /usr/bin/tee -a /etc/exports
Cmnd_Alias VAGRANT_NFSD_CHECK = /usr/bin/systemctl status nfs-server.service, /usr/sbin/systemctl status nfs-server.service
Cmnd_Alias VAGRANT_NFSD_START = /usr/bin/systemctl start nfs-server.service, /usr/sbin/systemctl start nfs-server.service
Cmnd_Alias VAGRANT_NFSD_APPLY = /usr/bin/exportfs -ar, /usr/sbin/exportfs -ar
Cmnd_Alias VAGRANT_EXPORTS_REMOVE = /bin/sed -r -e * d -ibak /tmp/exports, /usr/bin/cp /tmp/exports /etc/exports
%sudo ALL=(root) NOPASSWD: VAGRANT_EXPOSTS_UPDATE, VAGRANT_EXPORTS_ADD, VAGRANT_NFSD_CHECK, VAGRANT_NFSD_START, VAGRANT_NFSD_APPLY, VAGRANT_EXPORTS_REMOVE
EOF
vagrant plugin install vagrant-vbguest
vagrant plugin install vagrant-share
