---
- block:
  - command: kubectl --version
    register: kubectl_current_version
    changed_when: false
    failed_when: false
  - shell: "curl -sL https://api.github.com/repos/kubernetes/kubectl/tags | jq -r '[.[] | select(.name | ( contains(\"alpha\") or contains(\"beta\") or contains(\"rc\"))|not).name]|max_by( . | [splits(\"[.]\")])'"
    register: "kubectl_version"
  - block:
    - name: "Removing existing kubectl (v{{ kubectl_current_version.stdout_lines[0] }} )"
      file:
        path: "/usr/local/bin/kubectl"
        state: absent
    - name: 'downloading kubectl {{ kubectl_version.stdout_lines[0] }}'
      copy:
        src: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version.stdout_lines[0] }}/bin/linux/{{ architecture_map[ansible_architecture] }}/kubectl"
        dest: "/usr/local/bin/"
        mode: 0755
        owner: "root"
        group: "root"
        remote_src: yes
    become: yes
    when: 
      - kubectl_current_version.stdout is defined
      - kubectl_version.stdout_lines[0] not in kubectl_current_version.stdout
  become: yes
  